#!/bin/sh

. /home/victor/wordpress-5.2.3-0/scripts/setenv.sh

exec /home/victor/wordpress-5.2.3-0/php/sbin/.php-fpm.bin -y /home/victor/wordpress-5.2.3-0/php/etc/php-fpm.conf -p /home/victor/wordpress-5.2.3-0/php/var/ -c /home/victor/wordpress-5.2.3-0/php/etc/php.ini "$@"
