#!/bin/sh

. /home/victor/wordpress-5.2.3-0/scripts/setenv.sh
SASL_PATH="/home/victor/wordpress-5.2.3-0/common/lib/sasl2"
                export SASL_PATH
exec /home/victor/wordpress-5.2.3-0/common/sbin/.saslauthd.bin -f "/home/victor/wordpress-5.2.3-0/common/etc/sasldb2" "$@"
